### ISSUE TITLE
special treatment for 0 comparison

### ISSUE THREAD

**Issue by jpata** [slava77/cms-reco-tools#193]
It was noticed in [1] that a special treatment of variables that must be 0 within tolerance should be considered.

[1] https://github.com/cms-sw/cmssw/pull/31240#issuecomment-683658694

**Comment by slava77** [comment]
it may be more straightforward to elaborate here.
If something has a specific value, it's a specific value (without some "quantum" fluctuations).

If rerunning an algorithm leads to differences, they should be exposed/visible.

**Comment by jpata** [comment]
Perhaps we can think about an option to ignore floating-point differences in some cases when we know it is a false positive. However, since we basically build and compare histograms, this may not be feasible, and the cases where it's convenient may be rare (e.g. switching from one backend library to another, we might want to ignore tiny fp variations in order to catch big changes).

**Comment by slava77** [comment]
Looking more carefully at https://github.com/cms-sw/cmssw/pull/31240#issuecomment-683658694
I see that there is a problem with display of the exponent, it needs a fix in the offset for improved visibility.
That should be fixed.

For the case of "ignore numerical difference", it's really hard and will work only on very specific cases where these differences do not propagate downstream.

**Comment by jpata** [comment]
As was discussed in our reco chat, we don't find a use-case for ignoring small floating point differences in the comparison script. Minor differences early in reconstruction would propagate and likely result in more differences down the line, raising the question on what to ignore.
